version: "3.3"

services:

  # db:
  #   image: postgres
  #   restart: always
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #   networks:
  #     - sus-meter

  backend:
    image: node:18-alpine
    restart: always
    command: npm start
    working_dir: /backend
    volumes:
      - ./backend:/backend
    ports:
      - ${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}
    networks:
      - sus-meter
    env_file:
      - .env

  frontend:
    image: node:18-alpine
    restart: always
    command: npm run serve
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    ports:
      - ${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}
    networks:
      - sus-meter
    env_file:
      - .env

volumes:
  db-data:
    driver: local

networks:
  sus-meter:
    driver: bridge